version: "3"
services:
  client_dev:
    build: ./client
    command: sh -c "npm run dev"
    container_name: pc-client-dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    working_dir: /home/app/client
  api_dev:
    build: ./api
    command: sh -c "npm run migrate-db && npm run dev"
    container_name: pc-api-dev
    ports:
      - 3001:3001
    volumes:
      - ./api:/home/app/api
      - /home/app/api/node_modules
    working_dir: /home/app/api
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=next-ts-jwt-boilerplate
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data  
    ports:
      - 5432:5432